### ISSUE TITLE
-a | --archive flag issues

### ISSUE THREAD

**Issue by gotbletu** [deadc0de6/catcli#13]
doesn't seem to index the archives if the extension is not lowercase, e.g myfiles.**zip** vs myfiles.**ZIP**

`catcli index -a mystorage /run/media/user/mystorage`

```
#### not working
catcli ls -a mystorage/valet.ZIP

valet.ZIP: nothing found
```
----

```
#### working
catcli ls -a mystorage/valet.zip

valet.zip [size:96.6K]
- ARCHIVES.MNU [archive:valet.zip]
- FORMAT.MNU [archive:valet.zip]
- REGISTER.TXT [archive:valet.zip]
```

**Comment by deadc0de6** [comment]
Thanks for reporting this. It is now fixed in version 0.7.1!

**Comment by gotbletu** [comment]
just gave it a try on 0.7.1
created a new zip archive, rename it to ZIP extension
generated a new catcli.catalog
still getting the same issue, doesn't seem to work with capital cases for ZIP but lowercase zip works fine

```
aur/catcli-git 0.5.4.r0.gc69cd67-1 (+3 0.00) (Installed: 0.7.1.r0.g03f82f1-1)
OS: ArcoLinux
Kernel: 5.13.13-zen1-1-zen
```

**Comment by deadc0de6** [comment]
You're right, sorry my bad. Should be fixed in 0.7.2
